"""init schema (squashed)

Revision ID: 3f5b6a8c1a8c
Revises: 
Create Date: 2026-02-06 23:42:52.827401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f5b6a8c1a8c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('prefix_sku', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('prefix_sku')
    )
    op.create_table('company_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('amphoe', sa.String(length=100), nullable=True),
    sa.Column('province', sa.String(length=100), nullable=True),
    sa.Column('postcode', sa.String(length=10), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('tax_id', sa.String(length=32), nullable=True),
    sa.Column('logo_path', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('district', sa.String(length=120), nullable=True),
    sa.Column('amphoe', sa.String(length=120), nullable=True),
    sa.Column('province', sa.String(length=120), nullable=True),
    sa.Column('postcode', sa.String(length=10), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('tax_id', sa.String(length=32), nullable=True),
    sa.Column('contact_name', sa.String(length=120), nullable=True),
    sa.Column('contact_phone', sa.String(length=64), nullable=True),
    sa.Column('credit_term_days', sa.Integer(), nullable=True),
    sa.Column('payment_terms', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_name'), ['name'], unique=False)

    op.create_table('delivery_vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('plate_no', sa.String(length=50), nullable=True),
    sa.Column('capacity_note', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('license_no', sa.String(length=80), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('equipment_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=24), nullable=False),
    sa.Column('label_th', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('equipment_status', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_equipment_status_code'), ['code'], unique=True)

    op.create_table('gift_campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('cycle_months', sa.Integer(), nullable=False),
    sa.Column('anchor_month', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('promotion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('min_items', sa.Integer(), nullable=True),
    sa.Column('rental_unit', sa.String(length=6), nullable=True),
    sa.Column('min_duration', sa.Integer(), nullable=True),
    sa.Column('discount_type', sa.String(length=3), nullable=True),
    sa.Column('discount_value', sa.Float(), nullable=True),
    sa.Column('cheapest_units_to_discount', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('spare_parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('stock_qty', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint('stock_qty >= 0', name='ck_spare_parts_stock_qty_nonneg'),
    sa.CheckConstraint('unit_cost >= 0', name='ck_spare_parts_unit_cost_nonneg'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('spare_parts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spare_parts_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_spare_parts_name'), ['name'], unique=False)

    op.create_table('supplier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('tax_id', sa.String(length=32), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('amphoe', sa.String(length=100), nullable=True),
    sa.Column('province', sa.String(length=100), nullable=True),
    sa.Column('postcode', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('delivery_docs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=30), nullable=False),
    sa.Column('d_type', sa.Enum('DL', 'DLC', name='deliverytype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ONGOING', 'DONE', 'CANCELLED', name='deliverystatus'), nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('ship_to_name', sa.String(length=200), nullable=True),
    sa.Column('ship_to_phone', sa.String(length=80), nullable=True),
    sa.Column('ship_to_address', sa.Text(), nullable=True),
    sa.Column('ship_to_note', sa.String(length=255), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('schedule_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('cancel_reason_code', sa.String(length=20), nullable=True),
    sa.Column('cancel_reason_text', sa.String(length=255), nullable=True),
    sa.Column('reschedule_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['delivery_vehicles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    with op.batch_alter_table('delivery_docs', schema=None) as batch_op:
        batch_op.create_index('ix_delivery_unique_src', ['source_type', 'source_id'], unique=True)

    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=120), nullable=True),
    sa.Column('warehouse', sa.String(length=60), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('received_date', sa.Date(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('life_years', sa.Integer(), nullable=True),
    sa.Column('life_months', sa.Integer(), nullable=True),
    sa.Column('life_days', sa.Integer(), nullable=True),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_equipment_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_equipment_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_equipment_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_equipment_sku'), ['sku'], unique=True)
        batch_op.create_index(batch_op.f('ix_equipment_warehouse'), ['warehouse'], unique=False)

    op.create_table('gift_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tier_name', sa.String(length=50), nullable=True),
    sa.Column('times_achieved', sa.Integer(), nullable=False),
    sa.Column('last_achieved_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('last_given_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['gift_campaigns.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gift_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gift_results_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gift_results_customer_id'), ['customer_id'], unique=False)

    op.create_table('gift_tiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('min_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['gift_campaigns.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'code', name='uq_gift_tier_campaign_code')
    )
    op.create_table('purchase_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=32), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('po_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_order_number'), ['number'], unique=True)

    op.create_table('role_permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('perm_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['perm_id'], ['permission.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'perm_id', name='uq_role_perm')
    )
    with op.batch_alter_table('role_permission', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_permission_perm_id'), ['perm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_role_permission_role_id'), ['role_id'], unique=False)

    op.create_table('sales_doc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=32), nullable=True),
    sa.Column('doc_type', sa.String(length=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('warehouse', sa.String(length=60), nullable=True),
    sa.Column('project_name', sa.String(length=255), nullable=True),
    sa.Column('po_customer', sa.String(length=64), nullable=True),
    sa.Column('credit_days', sa.Integer(), nullable=True),
    sa.Column('tax_mode', sa.String(length=4), nullable=True),
    sa.Column('wht_pct', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('billing_mode', sa.String(length=12), nullable=True),
    sa.Column('contract_start', sa.Date(), nullable=True),
    sa.Column('contract_end', sa.Date(), nullable=True),
    sa.Column('installment_count', sa.Integer(), nullable=True),
    sa.Column('amount_subtotal', sa.Float(), nullable=True),
    sa.Column('amount_vat', sa.Float(), nullable=True),
    sa.Column('amount_total', sa.Float(), nullable=True),
    sa.Column('amount_wht', sa.Float(), nullable=True),
    sa.Column('amount_grand', sa.Float(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['sales_doc.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sales_doc', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_doc_number'), ['number'], unique=True)
        batch_op.create_index(batch_op.f('ix_sales_doc_warehouse'), ['warehouse'], unique=False)

    op.create_table('stock_reservation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(length=4), nullable=False),
    sa.Column('doc_id', sa.Integer(), nullable=False),
    sa.Column('sales_item_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=120), nullable=True),
    sa.Column('warehouse', sa.String(length=60), nullable=True),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_reservation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_reservation_brand'), ['brand'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_reservation_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_reservation_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_reservation_doc_id'), ['doc_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_reservation_warehouse'), ['warehouse'], unique=False)

    op.create_table('user_permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('perm_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['perm_id'], ['permission.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'perm_id', name='uq_user_perm')
    )
    with op.batch_alter_table('user_permission', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_permission_perm_id'), ['perm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_permission_user_id'), ['user_id'], unique=False)

    op.create_table('user_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_role')
    )
    with op.batch_alter_table('user_role', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_role_role_id'), ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_role_user_id'), ['user_id'], unique=False)

    op.create_table('claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=32), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'CLOSED', name='claim_status_enum'), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('billing_mode', sa.String(length=12), nullable=True),
    sa.Column('contract_start', sa.Date(), nullable=True),
    sa.Column('contract_end', sa.Date(), nullable=True),
    sa.Column('installment_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['sales_doc.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claims_number'), ['number'], unique=True)

    op.create_table('delivery_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_id', sa.Integer(), nullable=False),
    sa.Column('source_item_id', sa.Integer(), nullable=True),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('qty', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['doc_id'], ['delivery_docs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delivery_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doc_id'], ['delivery_docs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('delivery_photos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_delivery_photos_doc_id'), ['doc_id'], unique=False)

    op.create_table('equipment_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('customer_name', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('equipment_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_equipment_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_equipment_log_equipment_id'), ['equipment_id'], unique=False)

    op.create_table('equipment_price_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('equipment_price_plan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_equipment_price_plan_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_equipment_price_plan_equipment_id'), ['equipment_id'], unique=False)

    op.create_table('goods_receipt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=32), nullable=True),
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('grn_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('goods_receipt', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goods_receipt_number'), ['number'], unique=True)

    op.create_table('po_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=80), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=120), nullable=True),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.Column('discount_pct', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('po_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_po_item_po_id'), ['po_id'], unique=False)

    op.create_table('return_docs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=32), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=True),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('ref_type', sa.String(length=2), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['sales_doc.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['sales_doc.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('sales_installment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('installment_no', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('bill_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('po_customer_sub', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('amount_subtotal', sa.Float(), nullable=True),
    sa.Column('amount_vat', sa.Float(), nullable=True),
    sa.Column('amount_total', sa.Float(), nullable=True),
    sa.Column('amount_wht', sa.Float(), nullable=True),
    sa.Column('amount_grand', sa.Float(), nullable=True),
    sa.Column('bill_id', sa.Integer(), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('receipt_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['sales_doc.id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['sales_doc.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['sales_doc.id'], ),
    sa.ForeignKeyConstraint(['receipt_id'], ['sales_doc.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_id', 'installment_no', name='uq_sales_installment_contract_no')
    )
    with op.batch_alter_table('sales_installment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_installment_contract_id'), ['contract_id'], unique=False)

    op.create_table('sales_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('category_prefix', sa.String(length=50), nullable=True),
    sa.Column('brand', sa.String(length=120), nullable=True),
    sa.Column('allocated_skus', sa.Text(), nullable=True),
    sa.Column('line_status', sa.String(length=12), nullable=False),
    sa.Column('source_qu_item_id', sa.Integer(), nullable=True),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('qty', sa.Float(), nullable=True),
    sa.Column('rent_unit', sa.String(length=6), nullable=True),
    sa.Column('rent_duration', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('discount_pct', sa.Float(), nullable=True),
    sa.Column('line_subtotal', sa.Float(), nullable=True),
    sa.Column('line_total', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['doc_id'], ['sales_doc.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sales_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_item_doc_id'), ['doc_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_item_line_status'), ['line_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_item_source_qu_item_id'), ['source_qu_item_id'], unique=False)

    op.create_table('claim_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('sales_item_id', sa.Integer(), nullable=False),
    sa.Column('qty_claim', sa.Float(), nullable=False),
    sa.Column('replacement_equipment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['replacement_equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['sales_item_id'], ['sales_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grn_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grn_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=80), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=120), nullable=True),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['grn_id'], ['goods_receipt.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('grn_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grn_item_grn_id'), ['grn_id'], unique=False)

    op.create_table('return_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('condition', sa.String(length=16), nullable=True),
    sa.Column('damage_note', sa.Text(), nullable=True),
    sa.Column('damage_cost', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['doc_id'], ['return_docs.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incoming_equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grn_id', sa.Integer(), nullable=False),
    sa.Column('grn_item_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=120), nullable=True),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.Column('received_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['grn_id'], ['goods_receipt.id'], ),
    sa.ForeignKeyConstraint(['grn_item_id'], ['grn_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incoming_equipment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incoming_equipment_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_incoming_equipment_grn_id'), ['grn_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incoming_equipment_grn_item_id'), ['grn_item_id'], unique=False)

    op.create_table('repair_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=True),
    sa.Column('claim_item_id', sa.Integer(), nullable=True),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('symptom', sa.Text(), nullable=True),
    sa.Column('labor_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('parts_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['claim_item_id'], ['claim_items.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('repair_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('part_code', sa.String(length=64), nullable=True),
    sa.Column('part_name', sa.String(length=255), nullable=True),
    sa.Column('qty', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['repair_jobs.id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['spare_parts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repair_items')
    op.drop_table('repair_jobs')
    with op.batch_alter_table('incoming_equipment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incoming_equipment_grn_item_id'))
        batch_op.drop_index(batch_op.f('ix_incoming_equipment_grn_id'))
        batch_op.drop_index(batch_op.f('ix_incoming_equipment_created_at'))

    op.drop_table('incoming_equipment')
    op.drop_table('return_items')
    with op.batch_alter_table('grn_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grn_item_grn_id'))

    op.drop_table('grn_item')
    op.drop_table('claim_items')
    with op.batch_alter_table('sales_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_item_source_qu_item_id'))
        batch_op.drop_index(batch_op.f('ix_sales_item_line_status'))
        batch_op.drop_index(batch_op.f('ix_sales_item_doc_id'))

    op.drop_table('sales_item')
    with op.batch_alter_table('sales_installment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_installment_contract_id'))

    op.drop_table('sales_installment')
    op.drop_table('return_docs')
    with op.batch_alter_table('po_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_po_item_po_id'))

    op.drop_table('po_item')
    with op.batch_alter_table('goods_receipt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goods_receipt_number'))

    op.drop_table('goods_receipt')
    with op.batch_alter_table('equipment_price_plan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equipment_price_plan_equipment_id'))
        batch_op.drop_index(batch_op.f('ix_equipment_price_plan_created_at'))

    op.drop_table('equipment_price_plan')
    with op.batch_alter_table('equipment_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equipment_log_equipment_id'))
        batch_op.drop_index(batch_op.f('ix_equipment_log_created_at'))

    op.drop_table('equipment_log')
    with op.batch_alter_table('delivery_photos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_delivery_photos_doc_id'))

    op.drop_table('delivery_photos')
    op.drop_table('delivery_items')
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claims_number'))

    op.drop_table('claims')
    with op.batch_alter_table('user_role', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_role_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_role_role_id'))

    op.drop_table('user_role')
    with op.batch_alter_table('user_permission', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_permission_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_permission_perm_id'))

    op.drop_table('user_permission')
    with op.batch_alter_table('stock_reservation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_reservation_warehouse'))
        batch_op.drop_index(batch_op.f('ix_stock_reservation_doc_id'))
        batch_op.drop_index(batch_op.f('ix_stock_reservation_created_at'))
        batch_op.drop_index(batch_op.f('ix_stock_reservation_category_id'))
        batch_op.drop_index(batch_op.f('ix_stock_reservation_brand'))

    op.drop_table('stock_reservation')
    with op.batch_alter_table('sales_doc', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_doc_warehouse'))
        batch_op.drop_index(batch_op.f('ix_sales_doc_number'))

    op.drop_table('sales_doc')
    with op.batch_alter_table('role_permission', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_permission_role_id'))
        batch_op.drop_index(batch_op.f('ix_role_permission_perm_id'))

    op.drop_table('role_permission')
    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_order_number'))

    op.drop_table('purchase_order')
    op.drop_table('gift_tiers')
    with op.batch_alter_table('gift_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gift_results_customer_id'))
        batch_op.drop_index(batch_op.f('ix_gift_results_campaign_id'))

    op.drop_table('gift_results')
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equipment_warehouse'))
        batch_op.drop_index(batch_op.f('ix_equipment_sku'))
        batch_op.drop_index(batch_op.f('ix_equipment_name'))
        batch_op.drop_index(batch_op.f('ix_equipment_created_at'))
        batch_op.drop_index(batch_op.f('ix_equipment_category_id'))

    op.drop_table('equipment')
    with op.batch_alter_table('delivery_docs', schema=None) as batch_op:
        batch_op.drop_index('ix_delivery_unique_src')

    op.drop_table('delivery_docs')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    op.drop_table('supplier')
    with op.batch_alter_table('spare_parts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spare_parts_name'))
        batch_op.drop_index(batch_op.f('ix_spare_parts_code'))

    op.drop_table('spare_parts')
    op.drop_table('role')
    op.drop_table('promotion')
    op.drop_table('permission')
    op.drop_table('gift_campaigns')
    with op.batch_alter_table('equipment_status', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equipment_status_code'))

    op.drop_table('equipment_status')
    op.drop_table('drivers')
    op.drop_table('delivery_vehicles')
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_name'))
        batch_op.drop_index(batch_op.f('ix_customer_created_at'))

    op.drop_table('customer')
    op.drop_table('company_profile')
    op.drop_table('category')
    # ### end Alembic commands ###
