"""sync local sqlite schema

Revision ID: 99397497466d
Revises: c45c0a41dcd4
Create Date: 2025-12-03 10:40:40.174908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99397497466d'
down_revision = 'c45c0a41dcd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_doc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_doc', schema=None) as batch_op:
        batch_op.drop_column('project_name')

    # ### end Alembic commands ###
