"""change maintenance status to TH string

Revision ID: a81b19ccdc88
Revises: ef86f821ae63
Create Date: 2025-11-10 06:11:50.880819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a81b19ccdc88'
down_revision = 'ef86f821ae63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_jobs', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=16),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_jobs', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)

    # ### end Alembic commands ###
