"""add delivery_date to delivery_doc

Revision ID: b23d1e1e6924
Revises: 8b55a5ff1b32
Create Date: 2025-11-15 11:36:32.366374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b23d1e1e6924'
down_revision = '8b55a5ff1b32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('delivery_drivers')
    with op.batch_alter_table('delivery_docs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_docs', schema=None) as batch_op:
        batch_op.drop_column('delivery_date')

    op.create_table('delivery_drivers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=50), nullable=True),
    sa.Column('note', sa.VARCHAR(length=255), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
