"""your message

Revision ID: c45c0a41dcd4
Revises: e965f34ba2ce
Create Date: 2025-11-17 09:39:19.358395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c45c0a41dcd4'
down_revision = 'e965f34ba2ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('return_items', schema=None) as batch_op:
        batch_op.alter_column(
            'qty',
            existing_type=sa.NUMERIC(precision=10, scale=2),
            type_=sa.Integer(),
            existing_nullable=False
        )
        # ใส่ชื่อ foreign key constraint ให้เรียบร้อย
        batch_op.create_foreign_key(
            'fk_return_items_equipment_id',   # <- ชื่อ constraint
            'equipment',                      # ตารางปลายทาง
            ['equipment_id'],                 # column ฝั่ง return_items
            ['id']                            # column ฝั่ง equipment
        )
        batch_op.drop_column('equipment_name')
        batch_op.drop_column('sales_item_id')
        batch_op.drop_column('equipment_sku')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('return_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('equipment_sku', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('sales_item_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('equipment_name', sa.VARCHAR(length=255), nullable=True))
        # ต้องใช้ชื่อเดียวกับที่สร้างตอน upgrade
        batch_op.drop_constraint('fk_return_items_equipment_id', type_='foreignkey')
        batch_op.alter_column(
            'qty',
            existing_type=sa.Integer(),
            type_=sa.NUMERIC(precision=10, scale=2),
            existing_nullable=False
        )
    # ### end Alembic commands ###
