"""add gift campaign tables

Revision ID: df00395a7957
Revises: b23d1e1e6924
Create Date: 2025-11-16 23:41:39.836417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df00395a7957'
down_revision = 'b23d1e1e6924'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gift_campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('cycle_months', sa.Integer(), nullable=False),
    sa.Column('anchor_month', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gift_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tier_name', sa.String(length=50), nullable=True),
    sa.Column('times_achieved', sa.Integer(), nullable=False),
    sa.Column('last_achieved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['gift_campaigns.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gift_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gift_results_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gift_results_customer_id'), ['customer_id'], unique=False)

    op.create_table('gift_tiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('min_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['gift_campaigns.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'code', name='uq_gift_tier_campaign_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gift_tiers')
    with op.batch_alter_table('gift_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gift_results_customer_id'))
        batch_op.drop_index(batch_op.f('ix_gift_results_campaign_id'))

    op.drop_table('gift_results')
    op.drop_table('gift_campaigns')
    # ### end Alembic commands ###
