"""add warehouse_name to maintenance_jobs

Revision ID: ef86f821ae63
Revises: c9f1d2a8e7a1
Create Date: 2025-11-10 05:39:42.217234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef86f821ae63'
down_revision = 'c9f1d2a8e7a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('warehouse_name', sa.String(length=120), server_default='', nullable=False))
        batch_op.add_column(sa.Column('symptom', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('summary', sa.Text(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_maintenance_jobs_created_at'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maintenance_jobs_created_at'), ['created_at'], unique=False)
        batch_op.drop_column('summary')
        batch_op.drop_column('symptom')
        batch_op.drop_column('warehouse_name')

    # ### end Alembic commands ###
