"""Add brand + incoming equipment

Revision ID: f8075cdc74c3
Revises: 99397497466d
Create Date: 2026-01-03 14:39:29.372923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8075cdc74c3'
down_revision = '99397497466d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand', sa.String(length=120), nullable=True))

    with op.batch_alter_table('grn_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand', sa.String(length=120), nullable=True))

    with op.batch_alter_table('po_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('po_item', schema=None) as batch_op:
        batch_op.drop_column('brand')

    with op.batch_alter_table('grn_item', schema=None) as batch_op:
        batch_op.drop_column('brand')

    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_column('brand')

    # ### end Alembic commands ###
